### ISSUE TITLE
customization removal

### ISSUE THREAD

**Issue by divital-coder** [ChrisTitusTech/mybash#22]
SO, i didn't really like the theme it turned out for my terminal prompt in foot. [Termina]
Can , someone please help me how can i remove the customization and restore defaults...

**Comment by bhaskar253** [comment]
If you just want to revert back to your old customisations and looks you have to replace the contents of current .bashrc file with contents of .bashrc.bak which stores your previous configuration. 

this command will do the above job:
`cp ~/.bashrc.bak ~/.bashrc`

then you can restart your terminal and it will be back as before.

Also, if you don't want the additional packages which were installed, for now you can manually remove them using your package manager.

**Comment by divital-coder** [comment]
Thank you so much for the assistance , i got it figured out on the day i raised this issue, But nevertheless , much appreciated.
