### ISSUE TITLE
Can i change color for elements in PS1?

### ISSUE THREAD

**Issue by Anstrofon** [ChrisTitusTech/mybash#38]
I would like change manually color scheme. But I can't find any mention of colors in .bashrc.

**Comment by RazoBeckett** [comment]
it's a [starship](starship.rs) prompt if you want to change colors and look you can do it in the file located at `~/.config/starship.toml` . check out the starship's [docs](https://starship.rs/config/)

**Comment by Anstrofon** [comment]
> Hey @Anstrofon ,
> It's a [starship](starship.rs) prompt if you want to change colors and look you can do it in the file located at `~/.config/starship.toml` 
> - check out the starship's [docs](https://starship.rs/config/)

Thanks. 🙏
