### ISSUE TITLE
it is not working right now with me after pull update today

### ISSUE THREAD

**Issue by Mdoh-20** [ChrisTitusTech/mybash#39]
after pull update today it want work any more so push some updates to fix this
bash: compdef: command not found...
bash: compdef: command not found...
bash: compdef: command not found...
bash: compdef: command not found...
bash: compdef: command not found...
bash: compdef: command not found...
bash: /home/.../.bashrc: line 732: syntax error: unexpected end of file
...@fedora:~$ 
i feel this about zsh 
when I type zsh I get this 
"...@fedora:~$ zsh
/home/.../zshrc:2: no such user or named directory: .
[...@fedora]~% which zsh
/usr/bin/zsh
" and I do not know how to fix it
before i pull today your script was working fine

**Comment by Deftsu-lab** [comment]
edit the .bashrc file and add a "}" in line 644 and comment out the first 6 compdef definitions of the block above.
