### ISSUE TITLE
LINUXTOOLBOXDIR="$HOME/linuxtoolbox" Defaults to /root/ dir

### ISSUE THREAD

**Issue by Repressed8077** [ChrisTitusTech/mybash#68]
Steps to Reproduce:
1. git clone https://github.com/ChrisTitusTech/mybash.git 
2. cd mybash
3. Run sudo ./setup.sh
After running the last command, linuxtoobox dir is created in the /root/ dir instead of the $HOME. This leads to the permission denied error after restarting the shell

**Comment by RazoBeckett** [comment]
it's a skill issue, read the [instructions](https://github.com/ChrisTitusTech/mybash#how-to-install) you are not suppose to run the setup.sh with sudo. @Repressed8077

**Comment by Repressed8077** [comment]
@RazoBeckett I already resolved the issue, thanks for pointing that out
