### ISSUE TITLE
LS displaying all directories 

### ISSUE THREAD

**Issue by yashkathe** [ChrisTitusTech/mybash#8]
- After installing from _arch-setup.sh_ the **ls** command started displaying all the directories including the hidden directories and hidden files.  
- Is it possible to restore the default behavior where ls only displays directories which are visible ?
- Also the output by ls doesn't seem to obey the font-color which is set.
- This is my original color scheme:    
![og](https://user-images.githubusercontent.com/62693195/199387311-b5bac974-fbb5-43f0-a3c2-0cc9a8634793.png)  
But the output from ls is like this:   
![bug1](https://user-images.githubusercontent.com/62693195/199387388-9a3719f2-921f-4e06-b0ab-a76ca023cdf9.png)

**Comment by phatboislym** [comment]
it is possible to restore the default behavior where `ls` only displays directories which are visible
you can do this by opening the .bashrc file and commenting out the alias for the `ls` command
`alias ls='ls -aFh --color=always'` on line 142
this should also fix the color issue you've mentioned
